# Generated by Django 5.0.3 on 2024-03-25 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='name',
            new_name='room',
        ),
    ]
